- name: Install nginx
  apt:
    name:
      - nginx
    state: present

- name: Configure nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    mode: '0644'

- name: Restart nginx
  service:
    name: nginx
    state: restarted
